# HID/IRQ/FDL objects included: Arch 7.1.9-arch1-2 has all three =y.
obj-m := snd-soc-sdca.o
snd-soc-sdca-y := sdca_functions.o sdca_device.o sdca_function_device.o \
		  sdca_regmap.o sdca_asoc.o sdca_ump.o \
		  sdca_hid.o sdca_interrupts.o sdca_jack.o sdca_fdl.o
